# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('DivisionName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.TextField()),
                ('LastName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.TextField(max_length=200)),
                ('LoweredRoleName', models.TextField(null=True)),
                ('Description', models.TextField(max_length=400)),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.TextField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('GoalsHomeTeam', models.IntegerField()),
                ('GoalsAwayTeam', models.IntegerField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SeasonName', models.TextField()),
                ('Active', models.BooleanField(default=False)),
                ('IsHidden', models.BooleanField(default=False)),
                ('SeasonStart', models.DateTimeField(auto_now_add=True)),
                ('SeasonEnd', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TeamName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('DivisionId', models.ForeignKey(db_column=b'DivisionId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Divisions')),
                ('SeasonId', models.ForeignKey(db_column=b'SeasonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Seasons')),
            ],
        ),
        migrations.CreateModel(
            name='TopNavigation',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TopMenu', models.TextField(max_length=300)),
                ('TopMenuDescription', models.TextField(max_length=500)),
                ('TopMenuLink', models.TextField(max_length=500)),
                ('TopMenuOrder', models.IntegerField()),
                ('TopParentId', models.TextField(max_length=400)),
                ('TopMenuExternal', models.IntegerField()),
                ('IsHidden', models.BooleanField(default=False)),
                ('RoleId', models.ForeignKey(db_column=b'RoleId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('VenueName', models.TextField()),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='AwayTeamId',
            field=models.ForeignKey(db_column=b'AwayTeamId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AwayTeam', to='NVSLOnline.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='DivisionId',
            field=models.ForeignKey(db_column=b'DivisionId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Divisions'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='HomeTeamId',
            field=models.ForeignKey(db_column=b'HomeTeamId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HomeTeam', to='NVSLOnline.Teams'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='SeasonId',
            field=models.ForeignKey(db_column=b'SeasonId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Seasons'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='VenueId',
            field=models.ForeignKey(db_column=b'VenueId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Venues'),
        ),
        migrations.AddField(
            model_name='players',
            name='TeamId',
            field=models.ForeignKey(db_column=b'TeamId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.Teams'),
        ),
    ]
