# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopNavigation',
            new_name='TopNavigations',
        ),
    ]
