# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0002_auto_20170413_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationPages',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('TopMenu', models.TextField(max_length=300)),
                ('TopMenuLink', models.TextField(max_length=500)),
                ('TopMenuDescription', models.TextField(max_length=500)),
                ('IsHidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='topnavigations',
            name='TopMenu',
        ),
        migrations.RemoveField(
            model_name='topnavigations',
            name='TopMenuDescription',
        ),
        migrations.RemoveField(
            model_name='topnavigations',
            name='TopMenuLink',
        ),
        migrations.AlterField(
            model_name='topnavigations',
            name='TopMenuExternal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topnavigations',
            name='NavigationPageId',
            field=models.ForeignKey(db_column=b'NavigationPageId', null=True, on_delete=django.db.models.deletion.CASCADE, to='NVSLOnline.NavigationPages'),
        ),
    ]
