# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0003_auto_20170413_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topnavigations',
            name='NavigationPageId',
        ),
        migrations.AddField(
            model_name='topnavigations',
            name='TopMenu',
            field=models.TextField(default=19, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topnavigations',
            name='TopMenuDescription',
            field=models.TextField(default='Descr', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topnavigations',
            name='TopMenuLink',
            field=models.TextField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NavigationPages',
        ),
    ]
