# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NVSLOnline', '0005_auto_20170416_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='SeasonEnd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='SeasonStart',
            field=models.DateField(blank=True, null=True),
        ),
    ]
